#pragma once

enum eVehicleType
{
    VEHICLE_AUTOMOBILE,
    VEHICLE_MTRUCK,
    VEHICLE_QUAD,
    VEHICLE_HELI,
    VEHICLE_PLANE,
    VEHICLE_BOAT,
    VEHICLE_TRAIN,
    VEHICLE_FHELI,
    VEHICLE_FPLANE,
    VEHICLE_BIKE,
    VEHICLE_BMX,
    VEHICLE_TRAILER
};

enum VehicleUpgradePosn
{
    UPGRADE_BONNET,
    UPGRADE_BONNET_LEFT,
    UPGRADE_BONNET_RIGHT,
    UPGRADE_BONNET_DAM,
    UPGRADE_BONNET_LEFT_DAM,
    UPGRADE_BONNET_RIGHT_DAM,
    UPGRADE_SPOILER,
    UPGRADE_SPOILER_DAM,
    UPGRADE_WING_LEFT,
    UPGRADE_WING_RIGHT,
    UPGRADE_FRONTBULLBAR,
    UPGRADE_BACKBULLBAR,
    UPGRADE_LIGHTS,
    UPGRADE_LIGHTS_DAM,
    UPGRADE_ROOF,
    UPGRADE_NITRO,
};
